# Generated by Django 3.1.6 on 2021-02-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('E_id', models.AutoField(primary_key=True, serialize=False)),
                ('E_name', models.CharField(max_length=30)),
                ('E_mob', models.CharField(max_length=15)),
            ],
        ),
    ]
