# Generated by Django 3.1.6 on 2021-02-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPIApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyList',
            fields=[
                ('Prop_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PropertyName', models.CharField(max_length=60)),
                ('Proprety_Image', models.ImageField(upload_to='Property_images')),
                ('Property_Price', models.CharField(max_length=9)),
                ('Property_Description', models.TextField(max_length=180)),
                ('BuilderName', models.CharField(max_length=30)),
                ('Location', models.CharField(choices=[('Bangalore', 'Bangalore'), ('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Punjab', 'Punjab')], max_length=20)),
                ('PropertyAddress', models.CharField(max_length=100)),
                ('Area_in_sqft', models.CharField(max_length=6)),
                ('BHK', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=10)),
                ('PropertyStatus', models.CharField(choices=[('ongoing', 'ongoing'), ('completed', 'completed'), ('ready to move', 'ready to move')], max_length=20)),
                ('Avaliable_For', models.CharField(choices=[('buy', 'buy'), ('rent', 'rent')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
