# Generated by Django 3.1.6 on 2021-02-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPIApp', '0002_auto_20210207_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylist',
            name='Area_in_sqft',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='propertylist',
            name='Avaliable_For',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Rent', 'Rent')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propertylist',
            name='PropertyStatus',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Ready to move', 'Ready to move')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propertylist',
            name='Property_Price',
            field=models.CharField(max_length=10),
        ),
    ]
