# Generated by Django 3.1.6 on 2021-02-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPIApp', '0003_auto_20210207_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylist',
            name='Property_Type',
            field=models.CharField(choices=[('Residential', 'Residentail'), ('Commercial', 'Commercial')], default='Residential', max_length=20),
        ),
    ]
