# Generated by Django 3.1.6 on 2021-02-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPIApp', '0004_propertylist_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylist',
            name='Proprety_Image',
            field=models.ImageField(upload_to='static/Property_images'),
        ),
    ]
