# Generated by Django 3.1.6 on 2021-02-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPIApp', '0005_auto_20210207_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylist',
            name='BHK',
            field=models.CharField(choices=[('1bhk', '1bhk'), ('2bhk', '2bhk'), ('3bhk', '3bhk'), ('4bhk', '4bhk')], max_length=10),
        ),
    ]
