# Generated by Django 3.1.6 on 2021-02-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPIApp', '0006_auto_20210210_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylist',
            name='BHK',
            field=models.CharField(max_length=20),
        ),
    ]
