# Generated by Django 3.1.6 on 2021-02-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPIApp', '0007_auto_20210212_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylist',
            name='Avaliable_For',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Rent', 'Rent')], default='Sale', max_length=20),
        ),
    ]
