# Generated by Django 3.1.6 on 2021-02-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPIApp', '0008_auto_20210212_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylist',
            name='Avaliable_For',
            field=models.CharField(default='Sale', max_length=8),
        ),
    ]
