# Generated by Django 3.1.6 on 2021-02-13 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPIApp', '0009_auto_20210212_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Images', models.ImageField(upload_to='static/IndividualPropImgs')),
                ('Image_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTAPIApp.propertylist')),
            ],
        ),
    ]
