# Generated by Django 3.1.6 on 2021-02-13 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPIApp', '0010_propertyimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertylist',
            old_name='Proprety_Image',
            new_name='Property_Image',
        ),
    ]
